name: Daily Tech Digest Pipeline

on:
  schedule:
    # Run daily at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  daily-podcast-digest:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install additional dependencies for GitHub Actions environment
        pip install anthropic sqlite3
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg sqlite3
        
    - name: Restore database from previous run
      uses: actions/cache@v3
      with:
        path: |
          podcast_monitor.db
          audio_cache/
          transcripts/
        key: podcast-data-${{ github.run_number }}
        restore-keys: |
          podcast-data-
          
    - name: Set up environment variables
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> $GITHUB_ENV
        echo "ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
        
    - name: Run daily podcast pipeline
      run: |
        python3 daily_podcast_pipeline.py --run
        
    - name: Upload generated artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: podcast-digest-${{ github.run_number }}
        path: |
          daily_digests/
          transcripts/digested/
          podcast_monitor.db
        retention-days: 30
        
    - name: Commit and push changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily podcast digest update - $(date -u +%Y-%m-%d)"
          git push
        fi
        
    - name: Create release with digest
      if: success() && hashFiles('daily_digests/*.md') != ''
      uses: softprops/action-gh-release@v1
      with:
        tag_name: digest-${{ github.run_number }}
        name: Daily Tech Digest ${{ github.run_number }}
        files: |
          daily_digests/*.md
          daily_digests/*.mp3
        body: |
          Automated daily tech digest generated on $(date -u +%Y-%m-%d)
          
          Contains podcast summaries and audio from the latest tech episodes.